# Generated by Django 2.0 on 2018-01-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('content', models.TextField()),
                ('datapostagem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
